// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketsManagement.Data;

#nullable disable

namespace TicketsManagement.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20241017184827_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketsManagement.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TicketId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("TicketId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            Date = new DateTime(2024, 10, 12, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6044),
                            Description = "desc 1 ",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 2,
                            Date = new DateTime(2024, 10, 14, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6052),
                            Description = "desc 2",
                            Status = 1
                        },
                        new
                        {
                            TicketId = 3,
                            Date = new DateTime(2024, 10, 15, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6054),
                            Description = "desc 3",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 4,
                            Date = new DateTime(2024, 10, 16, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6055),
                            Description = "desc 4",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 5,
                            Date = new DateTime(2024, 10, 8, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6057),
                            Description = "desc 5 ",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 6,
                            Date = new DateTime(2024, 10, 14, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6059),
                            Description = "desc 6",
                            Status = 1
                        },
                        new
                        {
                            TicketId = 7,
                            Date = new DateTime(2024, 10, 15, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6060),
                            Description = "desc 7",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 8,
                            Date = new DateTime(2024, 10, 16, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6062),
                            Description = "desc 8",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 9,
                            Date = new DateTime(2024, 10, 12, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6063),
                            Description = "desc 9 ",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 10,
                            Date = new DateTime(2024, 10, 14, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6065),
                            Description = "desc 10",
                            Status = 1
                        },
                        new
                        {
                            TicketId = 11,
                            Date = new DateTime(2024, 10, 15, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6066),
                            Description = "desc 11",
                            Status = 0
                        },
                        new
                        {
                            TicketId = 12,
                            Date = new DateTime(2024, 10, 16, 18, 48, 26, 979, DateTimeKind.Utc).AddTicks(6068),
                            Description = "desc 12",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
